### ISSUE TITLE
Create Best Practices for Meetings & Events

### ISSUE THREAD

**Issue by m-branson** [mozilla/OSSN#14]
- [ ] Check if Matt has time and capacity to collect resources and best practices
Identify if there are resources already
- [x] MoFo (Amira?) - resources listed below
- [ ] Emma
- [ ] Ruben

Some ideas
- Meetings are held in safe, open and welcoming spaces.
- [ ] Designated 'greeter' person takes care of newcomers.
- [ ] Make clubs a safe place for different learning styles.
- [ ] Clubs provide a safe space for contributing.

**Comment by LucyeoH-zz** [comment]
Best Practices for [Events - Guide](https://docs.google.com/document/d/1ca4HJy6d9daAGguD64l0m2O6PZ8_oSzBCHPNTdJWKgU/edit#).

**Comment by LucyeoH-zz** [comment]
MOFO RESOURCES

[Events Guide for Women and Girls](http://mozilla.github.io/learning-networks/clubs/events-women-girls-guide/)

[Encouraging playful and participatory learning ](http://mozilla.github.io/learning-networks/clubs/encouraging-participatory-playful-learning/)

View these instructions on how you have to adapt your teaching style when teaching girls by Andrew Fuller.

Watch a video on [Uncovering Authentic Leadership ](https://womensleadership.stanford.edu/uncovering)with Professor Kenji Yoshino from NYU Law.

[Another video](https://air.mozilla.org/what-works-gender-equality-by-design-with-iris-bohnet/) on Gender Equality by Design with Iris Bohnet.

Strategies for educators to support females in STEM by Lynda R. Wiest.


http://mozilla.github.io/learning-networks/clubs/events-women-girls-guide/#resources

**Comment by LucyeoH-zz** [comment]
Should we prioritize a how-to about succession planning for OSSN. 
- Intro guide to OSSN 
- Here are the links

Topic for the community call? 
- Succession planning (how they're doing it between clubs, what works/what hasn't worked)
- Succession planning into OSSN
- What would they like to see form us to help their succession planning be successful

#81

**Comment by LucyeoH-zz** [comment]
Take from EWB folder!

**Comment by bacharakis** [comment]
Moved to sprint Eggplant
